### ISSUE TITLE
Screen filter switch doesn't have an effect in MiST's G'n'G

### ISSUE THREAD

**Issue by gyurco** [jotego/jtframe#1]
This
https://github.com/jotego/jtframe/blob/master/hdl/mist/jtframe_mist.v#L210
should be
    .en_mixing      ( en_mixing       ),

(and not inverted in the top-level), e.g.
    .en_mixing      ( status['hb]   ),
in jtgng_mist.v

**Comment by jotego** [comment]
Thanks a lot! It is fixed now.
