### ISSUE TITLE
OSD and control rotation behavior

### ISSUE THREAD

**Issue by gyurco** [jotego/jtframe#35]
It seems to be random which core actually rotate the OSD with rotate controls and which is not.
Also control rotation doesn't honor flip screen, for example in 1942, Rotate Controls Yes, then the controls are OK when Flip is Off, but not reversed when flip is On.
(And in 1942, the OSD stays in landscape mode even in a portrait usage)
For this purpose, I've written an arcade_controls module, which handles control rotation in every possible case:
https://github.com/mist-devel/mist-modules/blob/master/arcade_inputs.v
Maybe something similar can be added to jtframe, too.

**Comment by gyurco** [comment]
I see that MiST always get a landscape OSD (why?) and apply_rotation in jtframe_board can rotate the controls only in one direction. Maybe a flip option for this function could be used.

**Comment by jotego** [comment]
The OSD rotation comes from that extra byte in ROM with index 1. There needs to be an ARC file to make it work.

**Comment by jotego** [comment]
1942 seems to rotate the OSD ok, including the flip (after resetting the core). Maybe some ARC files are missing the extra byte.

**Comment by gyurco** [comment]
Hmm, there must be some problem with the MRA utility, since MOD=0 in 1942.ARC

**Comment by gyurco** [comment]
The problem is that the MRA contains:
```
<rom index="1">01</rom>
```
But should contain a part tag:
```
<rom index="1"><part>01</part></rom>
```

**Comment by gyurco** [comment]
And 1943, Gunsmoke, etc.. misses the whole rom index="1"
