### ISSUE TITLE
Add shadowmask feature

### ISSUE THREAD

**Issue by thehughhefner** [jotego/jtframe#56]
Hi Jotego,
When you have time, could you please add the shadow mask option the same way as in the MiSTer framework?

**Comment by jotego** [comment]
Hi, it was actually @atrac17  who added it in the first place. I think he has the intention to update it.

**Comment by atrac17** [comment]
Yes, I plan on updating it with other requested features in the near future @thehughhefner.

**Comment by jotego** [comment]
This is done now
