### ISSUE TITLE
MiST: second analog joystick on a gamepad

### ISSUE THREAD

**Issue by gyurco** [jotego/jtframe#58]
Recent firmware got support for 4 axes/gamepad, however testing is limited.
Usage is simple:
joystick_analog_n (where n is 0 or 1) was extended to 32 bit, [31:15] is the 2nd and 3rd axes.
https://github.com/mist-devel/mist-modules/blob/master/user_io.v#L43
Also digital signal is available at joystick_n [20:17], similarly to joystick_n[3:0] for the 1st and 2nd axes.

**Comment by jotego** [comment]
Brilliant!
