### ISSUE TITLE
Feature request: Support for HDMI pixel repetition

### ISSUE THREAD

**Issue by Toryalai1** [jotego/jtframe#71]
Hi Jotego,
Current MiSTer firmware has support for HDMI pixel repetition I wonder if you could consider adding this to your framework/cores as well. :)

**Comment by jotego** [comment]
Could you elaborate a bit more about it? What is this? Why is this useful? Is this something that just come with the MiSTer sys now?

**Comment by jotego** [comment]
Information from Toya:

Documentation: https://mister-devel.github.io/MkDocs_MiSTer/advanced/videomodes/?h=pixel#additional-flags
Original PR: https://github.com/MiSTer-devel/Template_MiSTer/pull/64/files

**Comment by jotego** [comment]
Feature added in commit 0d3ae6e. I will be recompiling and uploading the new cores during the following days (it takes some a long time to compile and test before breaking everybody's systems, and I'll probably end up breaking something anyway!)

**Comment by jotego** [comment]
BTW, thanks for bringing this topic up and thanks to Toya for checking a couple of test cases.
