### ISSUE TITLE
[Enhancement Request] - Save States

### ISSUE THREAD

**Issue by thehughhefner** [jotego/jtframe#95]
Hi Jotego,
Could you please look into adding save states to your cores? While released cores might be challenging, upcoming cores such as Neo geo pocket or upcoming arcade cores could be interesting.

**Comment by jotego** [comment]
I have designed the NGP CPU with that in mind, but I cannot commit to this requirement in general because it is a lot of extra work. If I can grow the team to have one full time developer, which I have tried twice but failed, I will re-consider it.
